// examples/react-css-only/src/App.tsx
import {
  NetworkId,
  WalletId,
  WalletManager,
  WalletProvider,
} from '@txnlab/use-wallet-react'
import {
  WalletButton,
  WalletUIProvider,
  type Theme,
} from '@txnlab/use-wallet-ui-react'
import { exportKeyPlugin } from '@txnlab/use-wallet-ui-react/plugins/export-key'
import { useState, useEffect } from 'react'

import { WalletInfo } from './components/WalletInfo'

import '@txnlab/use-wallet-ui-react/dist/style.css' // Import the pre-built CSS file
import './App.css'

const walletManager = new WalletManager({
  wallets: [
    WalletId.PERA,
    WalletId.DEFLY,
    WalletId.LUTE,
    WalletId.EXODUS,
    {
      id: WalletId.WALLETCONNECT,
      options: { projectId: 'fcfde0713d43baa0d23be0773c80a72b' },
    },
  ],
  defaultNetwork: NetworkId.TESTNET,
})

function App() {
  const [theme, setTheme] = useState<Theme>('system')

  // Sync app theme with the theme switcher
  // This adds/removes a 'dark' class on the root element
  useEffect(() => {
    const root = document.documentElement

    if (theme === 'dark') {
      root.classList.add('dark')
    } else if (theme === 'light') {
      root.classList.remove('dark')
    } else {
      // System preference
      const prefersDark = window.matchMedia(
        '(prefers-color-scheme: dark)',
      ).matches
      if (prefersDark) {
        root.classList.add('dark')
      } else {
        root.classList.remove('dark')
      }

      // Listen for system preference changes
      const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
      const handler = (e: MediaQueryListEvent) => {
        if (e.matches) {
          root.classList.add('dark')
        } else {
          root.classList.remove('dark')
        }
      }
      mediaQuery.addEventListener('change', handler)
      return () => mediaQuery.removeEventListener('change', handler)
    }
  }, [theme])

  return (
    <WalletProvider manager={walletManager}>
      <WalletUIProvider theme={theme} plugins={[exportKeyPlugin()]}>
        <div className="app-wrapper">
          {/* Header */}
          <header className="header">
            <div className="header-container">
              <div className="header-content">
                <div className="logo-container">
                  <span className="logo-text">use-wallet-ui</span>
                </div>
                <div className="wallet-controls">
                  {/* Theme selector */}
                  <select
                    value={theme}
                    onChange={(e) => setTheme(e.target.value as Theme)}
                    className="theme-select"
                  >
                    <option value="system">System</option>
                    <option value="light">Light</option>
                    <option value="dark">Dark</option>
                  </select>
                  <WalletButton />
                </div>
              </div>
            </div>
          </header>

          {/* Main content */}
          <main className="main-content">
            <div className="title-section">
              <h1 className="main-title">React Components for use-wallet</h1>
              <p className="description">
                A simple example demonstrating wallet connection, NFD profile
                integration, and balance display using the{' '}
                <code className="code-block">@txnlab/use-wallet-ui-react</code>{' '}
                package.
              </p>
              <p className="theme-info">
                Current theme: <code className="code-block">{theme}</code>
              </p>
            </div>

            {/* Account Info */}
            <WalletInfo />

            {/* Documentation Link */}
            <div className="footer">
              <p className="footer-text">
                View the{' '}
                <a
                  href="https://github.com/TxnLab/use-wallet-ui"
                  className="documentation-link"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  documentation
                </a>{' '}
                to learn more about implementing wallet integration in your
                dApp.
              </p>
            </div>
          </main>
        </div>
      </WalletUIProvider>
    </WalletProvider>
  )
}

export default App

// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue'
import {
  WalletUIProvider,
  WalletButton,
  type Theme,
} from '@txnlab/use-wallet-ui-vue'
import { exportKeyPlugin } from '@txnlab/use-wallet-ui-vue/plugins/export-key'

import WalletInfo from './components/WalletInfo.vue'

const theme = ref<Theme>('system')

// Sync app theme with the theme switcher
// This adds/removes a 'dark' class on the root element for Tailwind
watchEffect((onCleanup) => {
  const root = document.documentElement

  if (theme.value === 'dark') {
    root.classList.add('dark')
  } else if (theme.value === 'light') {
    root.classList.remove('dark')
  } else {
    // System preference
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')
    const applySystem = () => {
      if (mediaQuery.matches) {
        root.classList.add('dark')
      } else {
        root.classList.remove('dark')
      }
    }
    applySystem()
    mediaQuery.addEventListener('change', applySystem)
    onCleanup(() => mediaQuery.removeEventListener('change', applySystem))
  }
})
</script>

<template>
  <WalletUIProvider :theme="theme" :plugins="[exportKeyPlugin()]">
    <div class="min-h-screen bg-gray-50 dark:bg-slate-900">
      <!-- Header -->
      <header
        class="w-full bg-white dark:bg-slate-800/50 border-b border-gray-200 dark:border-slate-700/50"
      >
        <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="flex justify-between items-center h-16">
            <div class="flex-shrink-0">
              <span class="text-lg font-semibold text-gray-800 dark:text-white">
                use-wallet-ui
              </span>
            </div>
            <div class="flex items-center gap-4">
              <!-- Theme selector -->
              <select
                v-model="theme"
                class="text-sm px-2 py-1 rounded border border-gray-300 dark:border-slate-600 bg-white dark:bg-slate-800 text-gray-800 dark:text-white"
              >
                <option value="system">System</option>
                <option value="light">Light</option>
                <option value="dark">Dark</option>
              </select>
              <WalletButton />
            </div>
          </div>
        </div>
      </header>

      <!-- Content area -->
      <main class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div class="text-center mb-12">
          <h1 class="text-3xl font-bold text-gray-900 dark:text-white mb-4">
            Vue Components for use-wallet
          </h1>
          <p class="text-gray-600 dark:text-slate-300 max-w-2xl mx-auto">
            A simple example demonstrating wallet connection, NFD profile
            integration, and balance display using the
            <code
              class="text-sm bg-gray-100 dark:bg-slate-800 px-1.5 py-0.5 rounded"
            >
              @txnlab/use-wallet-ui-vue
            </code>
            package.
          </p>
          <p class="text-gray-500 dark:text-slate-400 text-sm mt-4">
            Current theme:
            <code class="bg-gray-100 dark:bg-slate-800 px-1.5 py-0.5 rounded">
              {{ theme }}
            </code>
          </p>
        </div>

        <WalletInfo />

        <div class="mt-8 text-center">
          <p class="text-sm text-gray-500 dark:text-slate-400">
            View the
            <a
              href="https://github.com/TxnLab/use-wallet-ui"
              class="text-blue-500 hover:text-blue-600 dark:text-blue-400 dark:hover:text-blue-300"
              target="_blank"
              rel="noopener noreferrer"
            >
              documentation
            </a>
            to learn more about implementing wallet integration in your dApp.
          </p>
        </div>
      </main>
    </div>
  </WalletUIProvider>
</template>
