// packages/vue/src/plugins/PluginSlot.vue
<script setup lang="ts">
import { h } from 'vue'
import { usePlugins } from './pluginContext'
import type { MenuRenderContext, MenuSlot } from './types'

const props = defineProps<{
  slot: MenuSlot
  ctx: MenuRenderContext
}>()

const { menuItemsBySlot } = usePlugins()
</script>

<template>
  <template v-for="item in menuItemsBySlot[props.slot]" :key="item.key">
    <component
      v-if="!item.enabled || item.enabled(props.ctx)"
      :is="() => h('div', {}, [item.render(props.ctx)])"
    />
  </template>
</template>

// packages/react/src/plugins/PluginSlot.tsx
import React from 'react'

import { usePlugins } from './PluginContext'

import type { MenuRenderContext, MenuSlot } from './types'

/**
 * Renders plugin menu items for a given slot.
 * Place this component at each named slot position in ConnectedWalletMenu.
 */
export function PluginSlot({
  slot,
  ctx,
}: {
  slot: MenuSlot
  ctx: MenuRenderContext
}) {
  const { menuItemsBySlot } = usePlugins()
  const items = menuItemsBySlot[slot]

  if (!items || items.length === 0) return null

  return (
    <>
      {items
        .filter((item) => !item.enabled || item.enabled(ctx))
        .map((item) => (
          <React.Fragment key={item.key}>{item.render(ctx)}</React.Fragment>
        ))}
    </>
  )
}
