// packages/vue/src/components/ConnectedWalletMenu.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { useFloating, offset, flip, shift } from '@floating-ui/vue'
import { useWallet } from '@txnlab/use-wallet-vue'
import { formatNumber, formatShortAddress } from '@txnlab/utils-ts'

import { useAccountInfo } from '../composables/useAccountInfo'
import { useNfd } from '../composables/useNfd'
import { usePlugins } from '../plugins/pluginContext'
import PluginSlot from '../plugins/PluginSlot.vue'
import { useWalletUI } from '../providers/walletUIContext'

import AlgoSymbol from './AlgoSymbol.vue'
import ConnectedWalletButton from './ConnectedWalletButton.vue'
import NfdAvatar from './NfdAvatar.vue'

import type { MenuRenderContext } from '../plugins/types'

const { activeAddress, activeWallet } = useWallet()
const { theme, resolvedTheme } = useWalletUI()
const { openDialog, closeDialog, panels } = usePlugins()

const referenceEl = ref<HTMLElement | null>(null)
const floatingEl = ref<HTMLElement | null>(null)
const { floatingStyles } = useFloating(referenceEl, floatingEl, {
  middleware: [offset(8), flip(), shift({ padding: 8 })],
  placement: 'bottom-end',
})

const isOpen = ref(false)
const activePanel = ref<string | null>(null)
const isCopied = ref(false)
const showAvailableBalance = ref(
  typeof localStorage !== 'undefined'
    ? localStorage.getItem('uwui:balance-preference') === 'available'
    : false,
)

const dataTheme = computed(() =>
  theme.value === 'system' ? undefined : theme.value,
)

const nfdQuery = useNfd()
const nfdName = computed(() => nfdQuery.data.value?.name ?? null)

const accountInfoQuery = useAccountInfo()

const totalBalance = computed(() => {
  const info = accountInfoQuery.data.value
  if (!info || info.amount === undefined) return null
  return Number(info.amount) / 1_000_000
})

const availableBalance = computed(() => {
  const info = accountInfoQuery.data.value
  if (!info || info.amount === undefined || info.minBalance === undefined)
    return null
  const available = Number(info.amount) - Number(info.minBalance)
  return Math.max(0, available / 1_000_000)
})

const displayBalance = computed(() =>
  showAvailableBalance.value ? availableBalance.value : totalBalance.value,
)

const pluginCtx = computed<MenuRenderContext>(() => ({
  activeAddress: activeAddress.value,
  activeWallet: activeWallet.value,
  theme: theme.value,
  resolvedTheme: resolvedTheme.value,
  closeMenu: () => {
    isOpen.value = false
  },
  openDialog,
  closeDialog,
  setActivePanel: (key) => {
    activePanel.value = key
  },
  activePanel: activePanel.value,
}))

const enabledPanels = computed(() =>
  panels.filter((p) => !p.enabled || p.enabled(pluginCtx.value)),
)

const currentPanel = computed(() =>
  activePanel.value ? panels.find((p) => p.key === activePanel.value) : null,
)

function renderCurrentPanel() {
  if (!currentPanel.value) return null
  return currentPanel.value.render({
    ctx: pluginCtx.value,
    goBack: () => {
      activePanel.value = null
    },
  })
}

function toggleMenu(): void {
  isOpen.value = !isOpen.value
  if (!isOpen.value) activePanel.value = null
}

function closeMenu(): void {
  isOpen.value = false
  activePanel.value = null
}

function handleCopyAddress(): void {
  if (!activeAddress.value) return
  navigator.clipboard.writeText(activeAddress.value)
  isCopied.value = true
  setTimeout(() => {
    isCopied.value = false
  }, 2000)
}

async function handleDisconnect(): Promise<void> {
  if (!activeWallet.value) return
  try {
    await activeWallet.value.disconnect()
    closeMenu()
  } catch (error) {
    console.error('Error disconnecting wallet:', error)
  }
}

function handleAccountChange(event: Event): void {
  const target = event.target as HTMLSelectElement
  const accountAddress = target.value
  if (activeWallet.value?.setActiveAccount) {
    activeWallet.value.setActiveAccount(accountAddress)
  }
}

function toggleBalanceView(): void {
  showAvailableBalance.value = !showAvailableBalance.value
  localStorage.setItem(
    'uwui:balance-preference',
    showAvailableBalance.value ? 'available' : 'total',
  )
}
</script>

<template>
  <div class="relative inline-block">
    <div ref="referenceEl" @click="toggleMenu">
      <slot>
        <ConnectedWalletButton />
      </slot>
    </div>

    <Teleport to="body">
      <div
        v-if="isOpen"
        data-wallet-theme
        data-wallet-ui
        :data-theme="dataTheme"
      >
        <div class="fixed inset-0 z-40" @mousedown.self="closeMenu" />

        <div
          ref="floatingEl"
          :style="floatingStyles"
          class="z-50 w-80 rounded-xl bg-[var(--wui-color-bg)] shadow-xl border border-[var(--wui-color-border)]"
        >
          <div class="p-4">
            <template v-if="currentPanel">
              <div class="flex items-center gap-2 mb-3">
                <button
                  @click="activePanel = null"
                  class="p-1 rounded-md hover:bg-[var(--wui-color-bg-secondary)] transition-colors text-[var(--wui-color-text-secondary)]"
                  aria-label="Back to menu"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="m15 18-6-6 6-6" />
                  </svg>
                </button>
                <h3 class="text-sm font-medium text-[var(--wui-color-text)]">
                  {{ currentPanel.label }}
                </h3>
              </div>
              <component v-if="currentPanel" :is="renderCurrentPanel" />
            </template>

            <template v-else>
              <div class="flex items-center gap-3 mb-4">
                <div class="h-12 w-12 overflow-hidden">
                  <NfdAvatar
                    :nfd="nfdQuery.data?.value"
                    :alt="`${nfdName || activeAddress} avatar`"
                    :size="48"
                  />
                </div>
                <div>
                  <h3
                    class="text-lg font-bold text-[var(--wui-color-text)] max-w-[220px] truncate wallet-custom-font"
                  >
                    {{
                      nfdName ||
                      (activeAddress
                        ? formatShortAddress(activeAddress, 6, 4)
                        : 'My Wallet')
                    }}
                  </h3>
                  <p
                    v-if="nfdName && activeAddress"
                    class="text-sm text-[var(--wui-color-text-secondary)]"
                  >
                    {{ formatShortAddress(activeAddress, 6, 4) }}
                  </p>
                </div>
              </div>

              <div
                class="mb-4 bg-[var(--wui-color-bg-secondary)] rounded-lg p-3"
              >
                <div class="flex justify-between items-center">
                  <span
                    v-if="displayBalance !== null"
                    class="text-base font-medium text-[var(--wui-color-text)] flex items-center gap-1"
                  >
                    {{ formatNumber(displayBalance, { fractionDigits: 4 }) }}
                    <AlgoSymbol />
                  </span>
                  <button
                    @click="toggleBalanceView"
                    class="flex items-center gap-1 text-sm text-[var(--wui-color-text-secondary)] bg-[var(--wui-color-bg-tertiary)] py-1 pl-2.5 pr-2 rounded-md hover:brightness-90 transition-all focus:outline-none"
                    :title="
                      showAvailableBalance
                        ? 'Show total balance'
                        : 'Show available balance'
                    "
                  >
                    {{ showAvailableBalance ? 'Available' : 'Total' }}
                  </button>
                </div>
              </div>

              <PluginSlot slot="after-balance" :ctx="pluginCtx" />

              <div
                v-if="
                  activeWallet?.accounts && activeWallet.accounts.length > 1
                "
                class="mb-4"
              >
                <label
                  class="block text-sm font-medium text-[var(--wui-color-text-secondary)] mb-1"
                >
                  Select Account
                </label>
                <select
                  :value="activeAddress || ''"
                  @change="handleAccountChange"
                  class="w-full rounded-lg border border-[var(--wui-color-border)] bg-[var(--wui-color-bg-secondary)] py-2 px-3 text-[var(--wui-color-text)] text-sm focus:outline-none"
                >
                  <option
                    v-for="account in activeWallet.accounts"
                    :key="account.address"
                    :value="account.address"
                  >
                    {{ formatShortAddress(account.address, 6, 4) }}
                  </option>
                </select>
              </div>

              <PluginSlot slot="after-accounts" :ctx="pluginCtx" />

              <div
                class="border-t border-[var(--wui-color-border)] mt-2 mb-2"
              />

              <div
                v-if="activeWallet"
                class="mb-2 flex items-center gap-2 px-1 py-0.5"
              >
                <div
                  class="h-5 w-5 overflow-hidden rounded flex items-center justify-center"
                >
                  <img
                    v-if="activeWallet.metadata.icon"
                    :src="activeWallet.metadata.icon"
                    :alt="`${activeWallet.metadata.name} icon`"
                    class="max-w-full max-h-full"
                  />
                </div>
                <p class="text-sm text-[var(--wui-color-text-secondary)]">
                  {{ activeWallet.metadata.name }}
                </p>
              </div>

              <PluginSlot slot="after-wallet-info" :ctx="pluginCtx" />
              <PluginSlot slot="before-actions" :ctx="pluginCtx" />

              <div
                v-if="enabledPanels.length > 0"
                class="flex flex-col gap-1 mb-2"
              >
                <button
                  v-for="panel in enabledPanels"
                  :key="panel.key"
                  @click="activePanel = panel.key"
                  class="w-full flex items-center justify-between py-2 px-2 rounded-lg text-sm text-[var(--wui-color-text)] hover:bg-[var(--wui-color-bg-secondary)] transition-colors"
                >
                  <span>{{ panel.label }}</span>
                  <span class="text-[var(--wui-color-text-tertiary)]">></span>
                </button>
              </div>

              <div
                class="border-t border-[var(--wui-color-border)] mb-3 mt-2"
              />

              <div class="flex gap-2">
                <button
                  @click="handleCopyAddress"
                  class="flex-1 py-2 px-4 bg-[var(--wui-color-bg-tertiary)] text-[var(--wui-color-text-secondary)] font-medium rounded-xl hover:brightness-90 transition-all text-sm"
                >
                  {{ isCopied ? 'Copied' : 'Copy Address' }}
                </button>
                <button
                  @click="handleDisconnect"
                  class="flex-1 py-2 px-4 bg-[var(--wui-color-danger-bg)] text-[var(--wui-color-danger-text)] font-medium rounded-xl hover:bg-[var(--wui-color-danger-bg-hover)] transition-all text-sm"
                >
                  Disconnect
                </button>
              </div>

              <PluginSlot slot="actions" :ctx="pluginCtx" />
            </template>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

// packages/react/src/components/ConnectedWalletMenu.tsx
import {
  useFloating,
  useClick,
  useDismiss,
  useInteractions,
  FloatingFocusManager,
  FloatingPortal,
  offset,
  flip,
  shift,
  autoUpdate,
  useId,
} from '@floating-ui/react'
import {
  Label,
  Listbox,
  ListboxButton,
  ListboxOption,
  ListboxOptions,
} from '@headlessui/react'
import { QueryClientProvider } from '@tanstack/react-query'
import { useWallet } from '@txnlab/use-wallet-react'
import { formatNumber, formatShortAddress } from '@txnlab/utils-ts'
import React, { ReactElement, RefObject, useState } from 'react'

import { useAccountInfo } from '../hooks/useAccountInfo'
import { useNfd } from '../hooks/useNfd'
import { usePlugins } from '../plugins/PluginContext'
import { PluginSlot } from '../plugins/PluginSlot'
import { useWalletUI } from '../providers/WalletUIProvider'

import { AlgoSymbol } from './AlgoSymbol'
import { ConnectedWalletButton } from './ConnectedWalletButton'
import { NfdAvatar } from './NfdAvatar'

import type { MenuRenderContext } from '../plugins/types'

// A more specific type for the children that includes ref
type RefableElement = ReactElement & {
  ref?: RefObject<HTMLElement> | ((instance: HTMLElement | null) => void)
}

export interface ConnectedWalletMenuProps {
  children?: RefableElement
}

function ConnectedWalletMenuContent({ children }: ConnectedWalletMenuProps) {
  const { activeAddress, activeWallet } = useWallet()
  const { theme, resolvedTheme } = useWalletUI()
  const { openDialog, closeDialog, panels } = usePlugins()
  const [isOpen, setIsOpen] = useState(false)
  const [activePanel, setActivePanel] = useState<string | null>(null)
  const [isCopied, setIsCopied] = useState(false)
  const [showAvailableBalance, setShowAvailableBalance] = useState(() => {
    // Try to get the stored preference from localStorage
    const stored = localStorage.getItem('uwui:balance-preference')
    return stored ? stored === 'available' : false
  })

  // Determine the data-theme attribute for the portal
  // Only set explicit themes, let 'system' use media query fallback
  const dataTheme = theme === 'system' ? undefined : theme

  // NFD for the active address
  const nfdQuery = useNfd({ enabled: !!activeAddress })
  const nfdName = nfdQuery.data?.name ?? null

  // Get account info for balance display
  const { data: accountInfo } = useAccountInfo({ enabled: !!activeAddress })

  // Calculate full and available balance
  const totalBalance = React.useMemo(() => {
    if (!accountInfo || accountInfo.amount === undefined) {
      return null
    }
    return Number(accountInfo.amount) / 1_000_000
  }, [accountInfo])

  const availableBalance = React.useMemo(() => {
    if (
      !accountInfo ||
      accountInfo.amount === undefined ||
      accountInfo.minBalance === undefined
    ) {
      return null
    }
    const available =
      Number(accountInfo.amount) - Number(accountInfo.minBalance)
    return Math.max(0, available / 1_000_000)
  }, [accountInfo])

  // Use appropriate balance based on toggle state
  const displayBalance = showAvailableBalance ? availableBalance : totalBalance

  const { refs, floatingStyles, context } = useFloating({
    open: isOpen,
    onOpenChange: (open) => {
      setIsOpen(open)
      if (!open) setActivePanel(null)
    },
    placement: 'bottom-end',
    middleware: [offset(8), flip(), shift()],
    whileElementsMounted: autoUpdate,
  })

  const click = useClick(context)
  const dismiss = useDismiss(context, { outsidePressEvent: 'mousedown' })
  const { getReferenceProps, getFloatingProps } = useInteractions([
    click,
    dismiss,
  ])

  const labelId = useId()

  const handleCopyAddress = () => {
    if (activeAddress) {
      navigator.clipboard.writeText(activeAddress)
      setIsCopied(true)
      setTimeout(() => setIsCopied(false), 2000)
    }
  }

  const handleDisconnect = async () => {
    if (activeWallet) {
      try {
        await activeWallet.disconnect()
        setIsOpen(false)
      } catch (error) {
        console.error('Error disconnecting wallet:', error)
      }
    }
  }

  const handleAccountChange = (accountAddress: string) => {
    if (activeWallet && activeWallet.setActiveAccount) {
      activeWallet.setActiveAccount(accountAddress)
    }
  }

  const toggleBalanceView = () => {
    const newValue = !showAvailableBalance
    setShowAvailableBalance(newValue)
    // Store the preference in localStorage
    localStorage.setItem(
      'uwui:balance-preference',
      newValue ? 'available' : 'total',
    )
  }

  // Build plugin render context with real closeMenu and dialog control
  const pluginCtx = React.useMemo<MenuRenderContext>(
    () => ({
      activeAddress,
      activeWallet,
      theme,
      resolvedTheme,
      closeMenu: () => setIsOpen(false),
      openDialog,
      closeDialog,
      setActivePanel,
      activePanel,
    }),
    [
      activeAddress,
      activeWallet,
      theme,
      resolvedTheme,
      openDialog,
      closeDialog,
      activePanel,
    ],
  )

  // Filter panels by enabled state
  const enabledPanels = React.useMemo(
    () => panels.filter((p) => !p.enabled || p.enabled(pluginCtx)),
    [panels, pluginCtx],
  )

  // Find the currently active panel definition
  const currentPanel = activePanel
    ? panels.find((p) => p.key === activePanel)
    : null

  // If no children are provided, create the default connected button
  const triggerElement = children || <ConnectedWalletButton />

  // Clone the trigger element with the reference props
  const trigger = React.cloneElement(
    triggerElement,
    getReferenceProps({ ref: refs.setReference }),
  )

  return (
    <>
      {trigger}
      {isOpen && (
        <FloatingPortal>
          <FloatingFocusManager context={context} modal={false}>
            <div data-wallet-theme data-wallet-ui data-theme={dataTheme}>
              <div
                ref={refs.setFloating}
                style={floatingStyles}
                {...getFloatingProps()}
                role="menu"
                aria-labelledby={labelId}
                className="z-50 w-80 rounded-xl bg-[var(--wui-color-bg)] shadow-xl border border-[var(--wui-color-border)]"
              >
                <div className="p-4">
                  {currentPanel ? (
                    /* Panel view */
                    <>
                      <div className="flex items-center gap-2 mb-3">
                        <button
                          onClick={() => setActivePanel(null)}
                          className="p-1 rounded-md hover:bg-[var(--wui-color-bg-secondary)] transition-colors text-[var(--wui-color-text-secondary)]"
                          aria-label="Back to menu"
                        >
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="16"
                            height="16"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <path d="m15 18-6-6 6-6" />
                          </svg>
                        </button>
                        <h3 className="text-sm font-medium text-[var(--wui-color-text)]">
                          {currentPanel.label}
                        </h3>
                      </div>
                      {currentPanel.render({
                        ctx: pluginCtx,
                        goBack: () => setActivePanel(null),
                      })}
                    </>
                  ) : (
                    /* Main menu view */
                    <>
                      <div className="flex items-center gap-3 mb-4">
                        <div className="h-12 w-12 overflow-hidden">
                          <NfdAvatar
                            nfd={nfdQuery.data}
                            alt={`${nfdName || activeAddress} avatar`}
                            size={48}
                          />
                        </div>
                        <div>
                          <h3
                            id={labelId}
                            className="text-lg font-bold text-[var(--wui-color-text)] max-w-[220px] truncate wallet-custom-font"
                          >
                            {nfdName ||
                              (activeAddress
                                ? formatShortAddress(activeAddress, 6, 4)
                                : 'My Wallet')}
                          </h3>
                          {nfdName && activeAddress && (
                            <p className="text-sm text-[var(--wui-color-text-secondary)]">
                              {formatShortAddress(activeAddress, 6, 4)}
                            </p>
                          )}
                        </div>
                      </div>

                      {/* Balance display with toggle */}
                      <div className="mb-4 bg-[var(--wui-color-bg-secondary)] rounded-lg p-3">
                        <div className="flex justify-between items-center">
                          {displayBalance !== null && (
                            <span className="text-base font-medium text-[var(--wui-color-text)] flex items-center gap-1">
                              {formatNumber(displayBalance, {
                                fractionDigits: 4,
                              })}
                              <AlgoSymbol />
                            </span>
                          )}
                          <button
                            onClick={toggleBalanceView}
                            className="flex items-center gap-1 text-sm text-[var(--wui-color-text-secondary)] bg-[var(--wui-color-bg-tertiary)] py-1 pl-2.5 pr-2 rounded-md hover:brightness-90 transition-all focus:outline-none"
                            title={
                              showAvailableBalance
                                ? 'Show total balance'
                                : 'Show available balance'
                            }
                          >
                            {showAvailableBalance ? 'Available' : 'Total'}
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              width="10"
                              height="10"
                              viewBox="0 0 24 24"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              className="ml-0.5 opacity-80"
                            >
                              <path d="m17 10-5-5-5 5" />
                              <path d="m17 14-5 5-5-5" />
                            </svg>
                          </button>
                        </div>
                      </div>

                      <PluginSlot slot="after-balance" ctx={pluginCtx} />

                      {/* Account selector (when multiple accounts available) */}
                      {activeWallet &&
                        activeWallet.accounts &&
                        activeWallet.accounts.length > 1 && (
                          <div className="mb-4">
                            <Listbox
                              value={activeAddress || ''}
                              onChange={handleAccountChange}
                            >
                              <Label className="block text-sm font-medium text-[var(--wui-color-text-secondary)] mb-1">
                                Select Account
                              </Label>
                              <div className="relative mt-1">
                                <ListboxButton className="grid w-full cursor-default grid-cols-1 rounded-lg border border-[var(--wui-color-border)] bg-[var(--wui-color-bg-secondary)] py-2 px-3 text-left text-[var(--wui-color-text)] shadow-sm focus:outline-none focus:ring-2 focus:ring-[var(--wui-color-primary)] focus:border-transparent text-sm">
                                  <span className="col-start-1 row-start-1 truncate pr-8">
                                    {activeAddress
                                      ? formatShortAddress(activeAddress, 6, 4)
                                      : 'Select account'}
                                  </span>
                                  <span className="col-start-1 row-start-1 self-center justify-self-end">
                                    <svg
                                      xmlns="http://www.w3.org/2000/svg"
                                      width="16"
                                      height="16"
                                      viewBox="0 0 16 16"
                                      fill="none"
                                      className="text-[var(--wui-color-text-secondary)]"
                                      aria-hidden="true"
                                    >
                                      <path
                                        d="M4 6L8 10L12 6"
                                        stroke="currentColor"
                                        strokeWidth="1.5"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                      />
                                    </svg>
                                  </span>
                                </ListboxButton>
                                <ListboxOptions
                                  transition
                                  className="absolute z-10 mt-1 max-h-60 w-full overflow-auto rounded-md bg-[var(--wui-color-bg-secondary)] py-1 shadow-lg ring-1 ring-black/5 focus:outline-none text-sm data-[closed]:data-[leave]:opacity-0 data-[leave]:transition data-[leave]:duration-100 data-[leave]:ease-in"
                                >
                                  {activeWallet.accounts.map((account) => (
                                    <ListboxOption
                                      key={account.address}
                                      value={account.address}
                                      className="group relative cursor-default select-none py-2 pl-3 pr-9 text-[var(--wui-color-text)] data-[focus]:bg-[var(--wui-color-bg-hover)] data-[focus]:outline-none"
                                    >
                                      <span className="block truncate font-normal group-data-[selected]:font-medium">
                                        {formatShortAddress(
                                          account.address,
                                          6,
                                          4,
                                        )}
                                      </span>
                                      <span className="absolute inset-y-0 right-0 flex items-center pr-3 text-[var(--wui-color-primary)] group-[&:not([data-selected])]:hidden">
                                        <svg
                                          xmlns="http://www.w3.org/2000/svg"
                                          width="16"
                                          height="16"
                                          viewBox="0 0 16 16"
                                          fill="none"
                                          className="h-5 w-5"
                                          aria-hidden="true"
                                        >
                                          <path
                                            d="M13.3334 4L6.00008 11.3333L2.66675 8"
                                            stroke="currentColor"
                                            strokeWidth="2"
                                            strokeLinecap="round"
                                            strokeLinejoin="round"
                                          />
                                        </svg>
                                      </span>
                                    </ListboxOption>
                                  ))}
                                </ListboxOptions>
                              </div>
                            </Listbox>
                          </div>
                        )}

                      <PluginSlot slot="after-accounts" ctx={pluginCtx} />

                      {/* Divider */}
                      <div className="border-t border-[var(--wui-color-border)] mt-2 mb-2" />

                      {/* Wallet info section */}
                      {activeWallet && (
                        <div className="mb-2 flex items-center gap-2 px-1 py-0.5">
                          <div className="h-5 w-5 overflow-hidden rounded flex items-center justify-center">
                            {activeWallet.metadata.icon ? (
                              <img
                                src={activeWallet.metadata.icon}
                                alt={`${activeWallet.metadata.name} icon`}
                                className="max-w-full max-h-full"
                              />
                            ) : (
                              <div className="h-5 w-5 rounded-full bg-[var(--wui-color-bg-tertiary)] flex items-center justify-center">
                                <svg
                                  xmlns="http://www.w3.org/2000/svg"
                                  className="h-3 w-3 text-[var(--wui-color-text-tertiary)]"
                                  viewBox="0 0 20 20"
                                  fill="currentColor"
                                >
                                  <path
                                    fillRule="evenodd"
                                    d="M17 9c0-.55-.45-1-1-1h-4c-.55 0-1 .45-1 1v8c0 .55.45 1 1 1h4c.55 0 1-.45 1-1V9zm-1 0v8h-4V9h4zM8 4c0-.55-.45-1-1-1H3c-.55 0-1 .45-1 1v13c0 .55.45 1 1 1h4c.55 0 1-.45 1-1V4zM3 3h4v14H3V3z"
                                    clipRule="evenodd"
                                  />
                                </svg>
                              </div>
                            )}
                          </div>
                          <p className="text-sm text-[var(--wui-color-text-secondary)]">
                            {activeWallet.metadata.name}
                          </p>
                        </div>
                      )}

                      <PluginSlot slot="after-wallet-info" ctx={pluginCtx} />

                      <PluginSlot slot="before-actions" ctx={pluginCtx} />

                      {/* Plugin panel triggers */}
                      {enabledPanels.length > 0 && (
                        <div className="flex flex-col gap-1 mb-2">
                          {enabledPanels.map((panel) => (
                            <button
                              key={panel.key}
                              onClick={() => setActivePanel(panel.key)}
                              className="w-full flex items-center justify-between py-2 px-2 rounded-lg text-sm text-[var(--wui-color-text)] hover:bg-[var(--wui-color-bg-secondary)] transition-colors"
                            >
                              <span className="flex items-center gap-2">
                                {panel.icon && (
                                  <panel.icon className="h-4 w-4 text-[var(--wui-color-text-secondary)]" />
                                )}
                                {panel.label}
                              </span>
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                width="14"
                                height="14"
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                className="text-[var(--wui-color-text-tertiary)]"
                              >
                                <path d="m9 18 6-6-6-6" />
                              </svg>
                            </button>
                          ))}
                        </div>
                      )}

                      {/* Divider */}
                      <div className="border-t border-[var(--wui-color-border)] mb-3 mt-2" />

                      {/* Action buttons */}
                      <div className="flex gap-2">
                        {/* Copy Address Button */}
                        <button
                          onClick={handleCopyAddress}
                          className="flex-1 py-2 px-4 bg-[var(--wui-color-bg-tertiary)] text-[var(--wui-color-text-secondary)] font-medium rounded-xl hover:brightness-90 transition-all text-sm flex items-center justify-center"
                          title="Copy address"
                        >
                          {isCopied ? (
                            <>
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                className="h-4 w-4 text-green-500 mr-1.5"
                                viewBox="0 0 20 20"
                                fill="currentColor"
                              >
                                <path
                                  fillRule="evenodd"
                                  d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                  clipRule="evenodd"
                                />
                              </svg>
                              Copied
                            </>
                          ) : (
                            <>
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                className="h-4 w-4 mr-1.5"
                                viewBox="0 0 20 20"
                                fill="currentColor"
                              >
                                <path d="M8 3a1 1 0 011-1h2a1 1 0 110 2H9a1 1 0 01-1-1z" />
                                <path d="M6 3a2 2 0 00-2 2v11a2 2 0 002 2h8a2 2 0 002-2V5a2 2 0 00-2-2 3 3 0 01-3 3H9a3 3 0 01-3-3z" />
                              </svg>
                              Copy
                            </>
                          )}
                        </button>

                        <PluginSlot slot="actions" ctx={pluginCtx} />

                        {/* Disconnect Button */}
                        <button
                          onClick={handleDisconnect}
                          className="flex-1 py-2 px-4 bg-[var(--wui-color-danger-bg)] text-[var(--wui-color-danger-text)] font-medium rounded-xl hover:bg-[var(--wui-color-danger-bg-hover)] transition-colors text-sm"
                        >
                          Disconnect
                        </button>
                      </div>
                    </>
                  )}
                </div>
              </div>
            </div>
          </FloatingFocusManager>
        </FloatingPortal>
      )}
    </>
  )
}

// Need to provide the QueryClientProvider here because FloatingPortal breaks context inheritance
export function ConnectedWalletMenu(props: ConnectedWalletMenuProps) {
  const { queryClient } = useWalletUI()

  return (
    <QueryClientProvider client={queryClient}>
      <ConnectedWalletMenuContent {...props} />
    </QueryClientProvider>
  )
}
